#!/bin/sh

# f-secure-autoupdate -- Update the definitions for F-Secure AV
#
# jkf, 25/08/03
#
#   MailScanner - SMTP Email Processor
#   Copyright (C) 2001  Julian Field
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#      https://www.mailscanner.info
#
# $Id: f-secure-autoupdate 4597 2008-12-11 01:50:19Z sysjkf $

Root=$1
# Dispose of Root
shift
# Dispose of Lock file name
shift
exec $Root/bin/dbupdate "$@"

