#!/bin/sh

# f-secure-12-wrapper --	invoke F-Secure AV for use with
# 			mailscanner
#
#   MailScanner - SMTP Email Processor
#   Copyright (C) 2021 MailScanner Team <https://mailscanner.info>
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#      https://www.mailscanner.info
#

Root=$1
shift

FS_SCAN=fsanalyze
PackageDir=$Root/bin
ScanOptions="--quiet --scan-archives=yes --detect-encrypted-archives=yes  --malware=remove --pua=remove"

if [ "x$1" = "x-IsItInstalled" ]; then
  [ -x ${PackageDir}/${FS_SCAN} ] && exit 0
  exit 1
fi

exec ${PackageDir}/${FS_SCAN} $ScanOptions "$@"