#!/usr/bin/perl -U -I /usr/share/MailScanner/perl
#
#   MailScanner - SMTP Email Processor
#   Copyright (C) 2018  MailScanner Project
#
#   $Id: mailscanner.sbin 5102 2011-08-20 12:31:59Z sysjkf $
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#      https://www.mailscanner.info
#

use strict;
no strict 'subs';
use POSIX;
require 5.005;

# chdir to a known good working directory
# Avoids permissions issues with current working directory
chdir('/usr/share/MailScanner/perl');

require "MailScanner/Milter.pm";

1;
