#!/bin/sh

#   MailScanner - SMTP Email Processor
#   Copyright (C) 2001  Julian Field
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#      https://www.mailscanner.info
#

PackageDir=$1
shift
prog=bdc
extras=''

#LogFile=/tmp/log.bdc.$$
LogFile=$(mktemp) || { echo "$0: Cannot create temporary file" >&2; exit 1; }

if [ -x ${PackageDir}/bdscan ]; then
  # Version 7.5 is installed
  prog=bdscan
  extras='--log-overwrite'
elif [ -x ${PackageDir}/bin/bdscan ]; then
  # Version 7.5 is installed, PackageDir is too short
  PackageDir=${PackageDir}/bin
  prog=bdscan
  extras='--log-overwrite'
elif [ -x ${PackageDir}/$prog ]; then
  # New version is installed
  :
else
  # Old version is installed
  PackageDir=${PackageDir}/shared
  export PackageDir
fi

if [ "x$1" = "x-IsItInstalled" ]; then
  rm -f $LogFile
  [ -x ${PackageDir}/$prog ] && exit 0
  exit 1
fi

umask 077
rm -f $LogFile
${PackageDir}/$prog --log=$LogFile $extras "$@" >/dev/null 2>&1
cat $LogFile
rm -f $LogFile
exit 0
