# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Execute builds
      run: ./Build.all
        
    - name: Upload builds
      uses: actions/upload-artifact@v4
      with:
        # Artifact name
        name: builds
        # A file, directory or wildcard pattern that describes what to upload
        path: ~/msbuilds/*
  test:
    needs: [build]
    name: Test install on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          # Artifact name
          name: builds
          # Destination path
          path: ./msbuilds/
      - name: install package
        run: sudo /usr/bin/dpkg -i ./msbuilds/MailScanner*deb
  clean:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Cleanup artifacts
        uses: GeekyEggo/delete-artifact@v1.0.0
        with:
          name: builds
          failOnError: false
